# Series
oktolab_series:
    path:      /oktolab_media/series/index
    defaults:  { _controller: OktolabMediaBundle:Series:index }

oktolab_series_show:
    path:       /oktolab_media/series/show/{series}
    defaults:   { _controller: OktolabMediaBundle:Series:show }

oktolab_series_new:
    path:       /oktolab_media/series/new
    defaults:   { _controller: OktolabMediaBundle:Series:new }

oktolab_series_edit:
    path:       /oktolab_media/series/{series}/edit
    defaults:   { _controller: OktolabMediaBundle:Series:edit }

oktolab_media_remote_seriess:
    path:       /oktolab_media/series/remote/{keychain}
    defaults:   { _controller: OktolabMediaBundle:Series:listRemoteSeriess }

oktolab_media_import_remote_series:
    path:       /oktolab_media/series/import/{keychain}
    defaults:   { _controller: OktolabMediaBundle:Series:importRemoteSeriess }

oktolab_media_export_series:
    path:       /oktolab_media/series/export/{series}
    defaults:   { _controller: OktolabMediaBundle:Series:export }

# Episodes
oktolab_episode_show:
    path:       /oktolab_media/episode/{uniqID}
    defaults:   { _controller: OktolabMediaBundle:Episode:show }

oktolab_episode_new:
    path:       /oktolab_media/episode/new
    defaults:   { _controller: OktolabMediaBundle:Episode:new }

oktolab_episode_edit:
    path:       /oktolab_media/episode/{episode}/edit
    defaults:   { _controller: OktolabMediaBundle:Episode:edit }

oktolab_media_remote_episodes:
    path:       /oktolab_media/episode/remote/{keychain}
    defaults:   { _controller: OktolabMediaBundle:Episode:listRemoteEpisodes }

oktolab_episode_index:
    path:       /oktolab_media/episodes
    defaults:   { _controller: OktolabMediaBundle:Episode:index }

oktolab_media_export_episode:
    path:       /oktolab_media/episode/{uniqID}/export
    defaults:   { _controller: OktolabMediaBundle:Episode:export }

oktolab_media_reimport_episode:
    path:       /oktolab_media/episode/reimport/{uniqID}
    defaults:   { _controller: OktolabMediaBundle:Episode:reimportEpisode }


# Media
oktolab_media_index:
    path:       /oktolab_media/media/index
    defaults:   { _controller: OktolabMediaBundle:Media:index }

oktolab_media_media_for_episode:
    path:       /oktolab_media/media/media_for_episode/{uniqID}
    defaults:   { _controller: OktolabMediaBundle:Media:mediaForEpisode }

oktolab_media_new_media:
    path:       /oktolab_media/media/new/{uniqID}
    defaults:   { _controller: OktolabMediaBundle:Media:new }

oktolab_media_show_media:
    path:       /oktolab_media/media/{media}
    defaults:   { _controller: OktolabMediaBundle:Media:show }

oktolab_media_edit_media:
    path:       /oktolab_media/media/{media}/edit
    defaults:   { _controller: OktolabMediaBundle:Media:edit }

oktolab_media_progress_media:
    path:       /oktolab_media/media/{media}/progress
    defaults:   { _controller: OktolabMediaBundle:Media:progress }

# Caption
oktolab_caption_index:
    path:       /oktolab_media/caption/
    defaults:   { _controller: OktolabMediaBundle:Caption:index }
oktolab_caption_show:
    path:       /oktolab_media/caption/show/{caption}
    defaults:   { _controller: OktolabMediaBundle:Caption:show }
oktolab_caption_edit:
    path:       /oktolab_media/caption/edit/{caption}
    defaults:   { _controller: OktolabMediaBundle:Caption:edit }
oktolab_caption_new:
    path:       /oktolab_media/caption/new/{uniqID}
    defaults:   { _controller: OktolabMediaBundle:Caption:new }

# Stream
oktolab_media_stream_new:
    path:       /oktolab_media/stream
    defaults:   { _controller: OktolabMediaBundle:Stream:new }

oktolab_media_stream_index:
    path:       /oktolab_media/stream/index
    defaults:   { _controller: OktolabMediaBundle:Stream:index }

oktolab_media_stream_show:
    path:       /oktolab_media/stream/show/{uniqID}
    defaults:   { _controller: OktolabMediaBundle:Stream:show }

oktolab_media_stream_edit:
    path:       /oktolab_media/stream/edit/{uniqID}
    defaults:   { _controller: OktolabMediaBundle:Stream:edit }

oktolab_media_stream_record:
    path:       /oktolab_media/stream/record
    defaults:   { _controller: OktolabMediaBundle:Stream:record }

oktolab_media_stream_redirect:
    path:       /oktolab_media/stream/redirect
    defaults:   { _controller: OktolabMediaBundle:Stream:redirect }

oktolab_media_stream_drop:
    path:       /oktolab_media/stream/drop
    defaults:   { _controller: OktolabMediaBundle:Stream:drop }

# keychain
oktolab_media_list_keychains:
    path:       /oktolab_media/list_keychains
    defaults:   { _controller: OktolabMediaBundle:Keychain:listKeychains }

oktolab_media_show_keychain:
    path:       /oktolab_media/show_keychain/{keychain}
    defaults:   { _controller: OktolabMediaBundle:Keychain:showKeychain }

oktolab_media_show_keychain_series:
    path:       /show_keychain/{keychain}/series/{uniqID}
    defaults:   { _controller: OktolabMediaBundle:Keychain:showSeries }

oktolab_media_show_keychain_episode:
    path:       /show_keychain/{keychain}/episode/{uniqID}
    defaults:   { _controller: OktolabMediaBundle:Keychain:showEpisode }

oktolab_media_local_import_episode:
    path:       /oktolab_media/import/episode
    defaults:   { _controller: OktolabMediaBundle:Keychain:importEpisode }

oktolab_media_local_import_series:
    path:       /oktolab_media/import/series
    defaults:   { _controller: OktolabMediaBundle:Keychain:importSeries }

# PRIVATE API ------------------------------------------------------------------
oktolab_media_api_list_series:
    path:       /oktolab_media/api/private/list/series.{_format}
    defaults:   { _controller: OktolabMediaBundle:MediaApi:listSeries, _format: json }
    requirements:
        _format: json

oktolab_media_api_show_series:
    path:       /oktolab_media/api/private/series.{_format}
    defaults:   { _controller: OktolabMediaBundle:MediaApi:showSeries, _format: json }
    requirements:
        _format: json|xml

oktolab_media_api_list_episodes:
    path:       /oktolab_media/api/private/list/episodes.{_format}
    defaults:   { _controller: OktolabMediaBundle:MediaApi:listEpisodes, _format: json }
    requirements:
        _format: json

oktolab_media_api_show_episode:
    path:       /oktolab_media/api/private/episode.{_format}
    defaults:   { _controller: OktolabMediaBundle:MediaApi:showEpisode, _format: json }
    requirements:
        _format: json|xml

oktolab_media_api_show_asset:
    path:       /oktolab_media/api/private/asset.{_format}
    defaults:   { _controller: OktolabMediaBundle:MediaApi:showAsset, _format: json}
    requirements:
        _format: json|xml

oktolab_media_api_import_series:
    path:       /oktolab_media/api/private/import/series
    defaults:   { _controller: OktolabMediaBundle:MediaApi:importSeries }

oktolab_media_api_import_episode:
    path:       /oktolab_media/api/private/import/episode
    defaults:   { _controller: OktolabMediaBundle:MediaApi:importEpisode }
# ------------------------------------------------------------------------------
#TODO: redefine api to use queries
#PUBLIC API --------------------------------------------------------------------
oktolab_media_player_for_episode:
    path:       /oktolab_media/api/public/episode/{uniqID}/{player_type}.{_format}
    defaults:   { _controller: OktolabMediaBundle:PublicApi:episode }

oktolab_media_caption_for_episode:
    path:       /oktolab_media/api/public/caption
    defaults:   { _controller: OktolabMediaBundle:PublicApi:caption }

oktolab_media_sprite_for_episode:
    path:       /oktolab_media/api/public/sprite
    defaults:   { _controller: OktolabMediaBundle:PublicApi:sprite }

oktolab_media_origin_for_episode:
    path:       /oktolab_media/api/public/origin.{_format}
    defaults:   { _controller: OktolabMediaBundle:PublicApi:origin, _format: json }
    requirements:
        _format: json

oktolab_media_embed_episode:
    path:       /oktolab_media/api/public/embed/episode
    defaults:   { _controller: OktolabMediaBundle:PublicApi:embedEpisode }

oktolab_media_series_show_posterframe:
    path:       /oktolab_media/api/public/posterframe/series
    defaults:   { _controller: OktolabMediaBundle:PublicApi:showSeriesPosterframe }

oktolab_media_check_streamstatus:
    path:       /oktolab_media/api/public/check_streamstatus
    defaults:   { _controller: OktolabMediaBundle:PublicApi:checkStreamStatus }

oktolab_media_check_streamkey:
    path:       /oktolab_media/api/public/check_streamkey
    defaults:   { _controller: OktolabMediaBundle:PublicApi:checkStreamkey }

oktolab_media_end_stream:
    path:       /oktolab_media/api/public/end_stream
    defaults:   { _controller: OktolabMediaBundle:PublicApi:endStream }
# ------------------------------------------------------------------------------
