services:
    oktolab_media:
        class:  Oktolab\MediaBundle\Model\MediaService
        arguments: [ "@bprs_jobservice", "@doctrine.orm.entity_manager", "@jms_serializer", %oktolab_media.episode_class%, %oktolab_media.series_class%, %bprs_asset.class%, %bprs_asset.adapters%, "@bprs_applink", "@bprs_logbook", "@event_dispatcher", "%oktolab_media.worker_queue%" ]

    oktolab_media_helper:
        class:  Oktolab\MediaBundle\Model\MediaHelperService
        arguments: [ "@doctrine.orm.entity_manager", "@bprs.asset", "@bprs_logbook", "@event_dispatcher", %bprs_asset.adapters%]

    oktolab_sprite:
        class:  Oktolab\MediaBundle\Model\SpriteService
        arguments: [ "@bprs.asset_helper", %oktolab_media.sprite_height%, %oktolab_media.sprite_width%, %oktolab_media.sprite_interval% ]

    origin:
        class: Oktolab\MediaBundle\Model\OriginService
        arguments: [ "@oktolab_media", "@bprs_applink", "@router" ]

    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
        public: false

    oktolab_media.asset_listener:
        class: Oktolab\MediaBundle\Event\AssetListener
        arguments: [ "@doctrine.orm.entity_manager", %oktolab_media.episode_class%, %oktolab_media.series_class%, %oktolab_media.media_class% ]
        tags:
            - { name: kernel.event_listener, event: bprs_asset.delete, method: onAssetDelete }

    oktolab_media.routing_loader:
        class: Oktolab\MediaBundle\Routing\AdvancedLoader
        tags:
            - { name: routing.loader }

    oktolab_keychain:
        class:      Oktolab\MediaBundle\Model\KeychainService
        arguments:  [ "@bprs_applink", "@jms_serializer", "%oktolab_media.serializing_schema%", "%oktolab_media.series_class%", "%oktolab_media.episode_class%"]

    # TWIG Extension
    oktolab_media.twig_extension:
        class: Oktolab\MediaBundle\Twig\PlayerExtension
        public: false
        arguments: [ "@twig", %oktolab_media.player_url%, %oktolab_media.player_type%, "@origin" ]
        tags:
            - { name: twig.extension }

    oktolab_media.episode_duration_twig_extension:
        class: Oktolab\MediaBundle\Twig\EpisodeDurationExtension
        public: false
        arguments: [ ]
        tags:
            - { name: twig.extension }

    # Commands
    oktolab_media.importEpisodeFromUrl_command:
        class:      Oktolab\MediaBundle\Command\ImportFromUrlCommand
        arguments:  [ "@oktolab_media", "@doctrine.orm.entity_manager"]
        tags:
            -  { name: console.command }

    # BPRSAppLinkAPIUrl
    oktolab_media_api:
        class: Oktolab\MediaBundle\Model\ApiUrlService
        arguments: [ "@router", %oktolab_media.api_urls%]

# LifecycleEvents
# cant inject specifig needed services due to
# https://github.com/doctrine/DoctrineBundle/issues/300
    oktolab_media_episode_lifecycle:
        class: Oktolab\MediaBundle\Event\EpisodeLifecycleListener
        arguments:  [ "@service_container" ]
        tags:
            - { name: doctrine.orm.entity_listener }
