services:
    oktolab_media:
        class:  Oktolab\MediaBundle\Model\MediaService
        arguments: [ @bprs_jobservice, @doctrine.orm.entity_manager, @jms_serializer, %oktolab_media.episode_class%, %oktolab_media.series_class%, %bprs_asset.class%, %bprs_asset.adapters% ]

    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
        public: false

    oktolab_media.asset_listener:
        class: Oktolab\MediaBundle\Event\AssetListener
        arguments: [ @doctrine.orm.entity_manager, %oktolab_media.episode_class%, %oktolab_media.series_class% ]
        tags:
            - { name: kernel.event_listener, event: bprs_asset.delete, method: onAssetDelete }

    oktolab_media.routing_loader:
        class: Oktolab\MediaBundle\Routing\AdvancedLoader
        tags:
            - { name: routing.loader }
