services:
    oktolab_media:
        class:  Oktolab\MediaBundle\Model\MediaService
        arguments: [ @bprs_jobservice, @doctrine.orm.entity_manager, @jms_serializer, @guzzle.client, %oktolab_media.episode_class%, %oktolab_media.series_class%, %bprs_asset.adapters% ]
